site_name: Omeka S User Manual
theme:
    name: 'readthedocs'
    custom_dir: 'omeka/'
    include_homepage_in_sidebar: true
site_url: 'https://omeka.org/s/'
repo_url: 'http://github.com/omeka/omeka-s-enduser'
extra_css:
    - css/extra.css
markdown_extensions:
    - admonition
    - attr_list
    - toc:
        permalink: ÔÉÅ
nav:
    - index.md
    - accessibility.md
    - s-planning-tips.md
    - install.md
    - admin-dashboard.md
    - glossary.md
    - search.md
    - frontpage.md
    - Sites:
        - sites/index.md
        - sites/site_settings.md
        - sites/site_pages.md
        - sites/site_navigation.md
        - sites/site_resources.md
        - sites/site_users.md
        - sites/site_theme.md
    - Resources:
        - content/items.md
        - content/media.md
        - content/item-sets.md
        - content/vocabularies.md
        - content/resource-template.md
    - Admin:
        - admin/users.md
        - admin/jobs.md
        - admin/settings.md
        - admin/assets.md
    - Modules:
        - modules/index.md
        - modules/activitylog.md
        - modules/collecting.md
        - modules/copyresources.md
        - modules/csseditor.md
        - modules/csvimport.md
        - modules/customvocab.md
        - modules/datacleaning.md
        - modules/datavisualization.md
        - modules/datarepositoryconnector.md
        - modules/dspaceconnector.md
        - modules/exports.md
        - modules/extractmetadata.md
        - modules/extracttext.md
        - modules/facetedbrowse.md
        - modules/fedoraconnector.md
        - modules/filesideload.md
        - modules/hierarchy.md
        - modules/iiifpresentation.md
        - modules/imageannotate.md
        - modules/inverseproperties.md
        - modules/itemcarouselblock.md
        - modules/localcontexts.md
        - modules/mapping.md
        - modules/metadatabrowse.md
        - modules/ndetermennetwerk.md
        - modules/numericdatatypes.md
        - modules/ohmsembed.md
        - modules/omekaCimporter.md
        - modules/ositemimporter.md
        - modules/outputformats.md
        - modules/persistentidentifiers.md
        - modules/redactvalues.md
        - modules/resourcemeta.md
        - Scripto:
            - modules/scripto/index.md
            - modules/scripto/scriptoproject.md
            - modules/scripto/themeingScripto.md
            - modules/scripto/scriptoPublicView.md
            - modules/scripto/troubleshootingScripto.md
        - modules/sharing.md
        - modules/staticsiteexport.md
        - modules/uridereferencer.md
        - modules/valuesuggest.md
        - modules/viewprivateresources.md
        - modules/zoterocitation.md
        - modules/zoteroimport.md
    - Miscellaneous:
        - errorLogging.md
        - translateOmekaS.md
        - configuration.md
        - importexport.md