site_name: Omeka S User Manual
theme: 
    name: 'readthedocs'
    custom_dir: 'omeka/'
    include_homepage_in_sidebar: false
repo_url: 'http://github.com/omeka/omeka-s-enduser'
extra_css:
    - css/extra.css
markdown_extensions:
    - toc:
        permalink: ÔÉÅ
nav:
    - index.md
    - accessibility.md
    - s-planning-tips.md
    - install.md
    - admin-dashboard.md
    - glossary.md
    - search.md
    - frontpage.md
    - Sites:
        - sites/index.md
        - sites/site_settings.md
        - sites/site_pages.md
        - sites/site_navigation.md
        - sites/site_resources.md
        - sites/site_users.md
        - sites/site_theme.md
    - Resources:
        - content/items.md
        - content/item-sets.md
        - content/media.md
        - content/vocabularies.md
        - content/resource-template.md
    - Admin:
        - admin/users.md
        - admin/jobs.md
        - admin/settings.md
    - Modules:
        - modules/index.md
        - modules/collecting.md
        - modules/csseditor.md
        - modules/csvimport.md
        - modules/customvocab.md
        - modules/dspaceconnector.md
        - modules/extracttext.md
        - modules/fedoraconnector.md
        - modules/filesideload.md
        - modules/mapping.md
        - modules/metadatabrowse.md
        - modules/numericdatatypes.md
        - modules/omeka2importer.md
        - Scripto:
            - modules/scripto/index.md
            - modules/scripto/scriptoproject.md
            - modules/scripto/themeingScripto.md
            - modules/scripto/scriptoPublicView.md
            - modules/scripto/troubleshootingScripto.md
        - modules/sharing.md
        - modules/valuesuggest.md
        - modules/zoteroimport.md
    - Miscellaneous:
        - errorLogging.md
        - translateOmekaS.md
        - configuration.md
