site_name: Omeka S User Manual
theme: 'readthedocs'
repo_url: 'http://github.com/omeka/omeka-s-enduser'
extra_css:
    - css/extra.css
pages:
    - 'Home': 'index.md'
    - 'Accessibility Statement': 'accessibility.md'
    - 'Planning Tips': 's-planning-tips.md'
    - 'Installing': 'install.md'
    - 'Admin Dashboard': 'admin-dashboard.md'
    - 'Glossary': 'glossary.md'
    - 'Searching': 'search.md'
    - 'Front Page': 'frontpage.md'
    - 'Sites': 
        - 'Sites Management': 'sites/index.md'
        - 'Site Admin': 'sites/site_settings.md'
        - 'Pages Management': 'sites/site_pages.md'
        - 'Navigation': 'sites/site_navigation.md'
        - 'Resources': 'sites/site_resources.md'
        - 'User Permissions': 'sites/site_users.md'
        - 'Theme Selection': 'sites/site_theme.md'
    - 'Resources':
        - 'Items': 'content/items.md'
        - 'Item Sets': 'content/item-sets.md'
        - 'Media': 'content/media.md'
        - 'Vocabularies': 'content/vocabularies.md'
        - 'Resource Templates': 'content/resource-template.md'
    - 'Admin':
        - 'Users': 'admin/users.md'
        - 'Jobs': 'admin/jobs.md'
        - 'Manage Settings': 'admin/settings.md'
    - 'Modules':
        - 'Modules Management': 'modules/index.md'
        - 'Collecting': 'modules/collecting.md'
        - 'CSS Editor': 'modules/csseditor.md'
        - 'CSV Import': 'modules/csvimport.md'
        - 'Custom Vocab': 'modules/customvocab.md'
        - 'DSpace Connector': 'modules/dspaceconnector.md'
        - 'Extract Text' : 'modules/extracttext.md'
        - 'Fedora Connector': 'modules/fedoraconnector.md'
        - 'File Sideload': 'modules/filesideload.md'
        - 'Mapping': 'modules/mapping.md'
        - 'Metadata Browse': 'modules/metadatabrowse.md'
        - 'Numeric Data Types': 'modules/numericdatatypes.md'
        - 'Omeka2 Importer': 'modules/omeka2importer.md'
        - 'Scripto':
            - 'Set up Scripto': 'modules/scripto/index.md'
            - 'Scripto Projects': 'modules/scripto/scriptoproject.md'
            - 'Themeing Scripto': 'modules/scripto/themeingScripto.md'
            - 'Public Interface': 'modules/scripto/scriptoPublicView.md'
            - 'Troubleshooting': 'modules/scripto/troubleshootingScripto.md'
        - 'Sharing': 'modules/sharing.md'
        - 'ValueSuggest': 'modules/valuesuggest.md'
        - 'Zotero Import': 'modules/zoteroimport.md'
    - 'Error Logging': 'errorLogging.md'
    - 'Translate Omeka S': 'translateOmekaS.md'
    - 'Configuration Options': 'configuration.md'
